#  ____
# |_  /_ _ __ _
#  / /| '_/ _` |
# /___|_| \__, |
#         |___/
# . bash_aliases for .bashrc
# . . . . . . . . . . . . . . . . . . . . .

alias ls='ls --color=auto'
alias sudo='sudo '

alias shutdown='shutdown -h now'
alias restart='shutdown -r now'

alias vpn='sudo openvpn --config ~/.private/vpn.ovpn'

alias fs='du -hd1 | sort -h'

alias ls='exa --git'
alias tree='exa -t'
alias lss='exa --sort=size -r -l' # sort by size - highest, up
